import * as React from 'react';

import { Provider as ProviderTheme } from './contexts/theme';
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </head>
      <body>
        <ProviderTheme>{children}</ProviderTheme>
      </body>
    </html>
  );
}
