export const metadata = {
  title: 'Dominó System Management',
  description: 'Generated by create next app'
};

export default function Login() {
  return (
    <main style={{ backgroundColor: 'black', height: '100vh' }}>
      <h1 style={{ color: 'cyan' }}>Login</h1>
    </main>
  );
}
